# Data Analysis Across All Datasets

In [208]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)

In [2]:
HD_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/HD_test_perf.csv")
HD_optimal_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/HD_optimal_test_perf.csv")
HD_optimal_train_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/HD_optimal_train_perf.csv")

DRUG_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/DRUG_test_perf.csv")
DRUG_optimal_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/DRUG_optimal_test_perf.csv")
DRUG_optimal_train_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/DRUG_optimal_train_perf.csv")

MUSH_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/MUSH_test_perf.csv")
MUSH_optimal_test_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/MUSH_optimal_test_perf.csv")
MUSH_optimal_train_df = pd.read_csv("~/Desktop/Winter_2020/Cogs_118A/FinalProject/Cogs118A_FinalProject/Data/MUSH_optimal_train_perf.csv")

## Average test performances in each dataset

In [3]:
HD_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.786885          0.750000         0.770492   
1         RF         0.803279          0.814815         0.754098   
2         LR         0.803279          0.793103         0.819672   
3         DT         0.770492          0.758621         0.721311   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.800000         0.868852          0.815789  
1          0.783784         0.934426          0.966667  
2          0.815789         0.918033          0.909091  
3          0.743590         0.852459          0.878788

In [106]:
HD_KNN_ACC = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
HD_KNN_ACC= pd.DataFrame({'Trial':HD_KNN_ACC.index, 'Accuracy':HD_KNN_ACC.values}).iloc[1:]
HD_KNN_ACC = HD_KNN_ACC.as_matrix(columns=HD_KNN_ACC.columns[1:])
HD_KNN_ACC

array([[0.7868850000000001],
       [0.770492],
       [0.8688520000000001]], dtype=object)

In [112]:
HD_RF_ACC = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
HD_RF_ACC= pd.DataFrame({'Trial':HD_RF_ACC.index, 'Accuracy':HD_RF_ACC.values}).iloc[1:]
HD_RF_ACC = HD_RF_ACC.as_matrix(columns=HD_RF_ACC.columns[1:])
HD_RF_ACC

array([[0.803279],
       [0.7540979999999999],
       [0.934426]], dtype=object)

In [113]:
HD_LR_ACC = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
HD_LR_ACC= pd.DataFrame({'Trial':HD_LR_ACC.index, 'Accuracy':HD_LR_ACC.values}).iloc[1:]
HD_LR_ACC = HD_LR_ACC.as_matrix(columns=HD_LR_ACC.columns[1:])
HD_LR_ACC

array([[0.803279],
       [0.819672],
       [0.918033]], dtype=object)

In [114]:
HD_DT_ACC = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
HD_DT_ACC= pd.DataFrame({'Trial':HD_DT_ACC.index, 'Accuracy':HD_DT_ACC.values}).iloc[1:]
HD_DT_ACC = HD_DT_ACC.as_matrix(columns=HD_DT_ACC.columns[1:])
HD_DT_ACC

array([[0.770492],
       [0.7213109999999999],
       [0.852459]], dtype=object)

In [107]:
HD_KNN_PREC = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
HD_KNN_PREC= pd.DataFrame({'Trial':HD_KNN_PREC.index, 'Accuracy':HD_KNN_PREC.values}).iloc[1:]
HD_KNN_PREC = HD_KNN_PREC.as_matrix(columns=HD_KNN_PREC.columns[1:])
HD_KNN_PREC

array([[0.75],
       [0.8],
       [0.815789]], dtype=object)

In [115]:
HD_RF_PREC = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
HD_RF_PREC= pd.DataFrame({'Trial':HD_RF_PREC.index, 'Accuracy':HD_RF_PREC.values}).iloc[1:]
HD_RF_PREC = HD_RF_PREC.as_matrix(columns=HD_RF_PREC.columns[1:])
HD_RF_PREC

array([[0.814815],
       [0.783784],
       [0.966667]], dtype=object)

In [116]:
HD_LR_PREC = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
HD_LR_PREC= pd.DataFrame({'Trial':HD_LR_PREC.index, 'Accuracy':HD_LR_PREC.values}).iloc[1:]
HD_LR_PREC = HD_LR_PREC.as_matrix(columns=HD_LR_PREC.columns[1:])
HD_LR_PREC

array([[0.793103],
       [0.815789],
       [0.909091]], dtype=object)

In [117]:
HD_DT_PREC = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
HD_DT_PREC= pd.DataFrame({'Trial':HD_DT_PREC.index, 'Accuracy':HD_DT_PREC.values}).iloc[1:]
HD_DT_PREC = HD_DT_PREC.as_matrix(columns=HD_DT_PREC.columns[1:])
HD_DT_PREC

array([[0.758621],
       [0.74359],
       [0.8787879999999999]], dtype=object)

In [4]:
DRUG_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.795756          0.875000         0.814324   
1         RF         0.801061          0.877470         0.795756   
2         LR         0.803714          0.859316         0.816976   
3         DT         0.774536          0.867769         0.782493   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.833977         0.793103          0.861004  
1          0.826772         0.777188          0.832090  
2          0.834615         0.811671          0.856618  
3          0.823293         0.763926          0.860656

In [108]:
DRUG_KNN_ACC = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
DRUG_KNN_ACC= pd.DataFrame({'Trial':DRUG_KNN_ACC.index, 'Accuracy':DRUG_KNN_ACC.values}).iloc[1:]
DRUG_KNN_ACC = DRUG_KNN_ACC.as_matrix(columns=DRUG_KNN_ACC.columns[1:])
DRUG_KNN_ACC

array([[0.795756],
       [0.8143239999999999],
       [0.793103]], dtype=object)

In [118]:
DRUG_RF_ACC = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
DRUG_RF_ACC= pd.DataFrame({'Trial':DRUG_RF_ACC.index, 'Accuracy':DRUG_RF_ACC.values}).iloc[1:]
DRUG_RF_ACC = DRUG_RF_ACC.as_matrix(columns=DRUG_RF_ACC.columns[1:])
DRUG_RF_ACC

array([[0.8010609999999999],
       [0.795756],
       [0.777188]], dtype=object)

In [119]:
DRUG_LR_ACC = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
DRUG_LR_ACC= pd.DataFrame({'Trial':DRUG_LR_ACC.index, 'Accuracy':DRUG_LR_ACC.values}).iloc[1:]
DRUG_LR_ACC = DRUG_LR_ACC.as_matrix(columns=DRUG_LR_ACC.columns[1:])
DRUG_LR_ACC

array([[0.803714],
       [0.816976],
       [0.811671]], dtype=object)

In [120]:
DRUG_DT_ACC = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
DRUG_DT_ACC= pd.DataFrame({'Trial':DRUG_DT_ACC.index, 'Accuracy':DRUG_DT_ACC.values}).iloc[1:]
DRUG_DT_ACC = DRUG_DT_ACC.as_matrix(columns=DRUG_DT_ACC.columns[1:])
DRUG_DT_ACC

array([[0.774536],
       [0.782493],
       [0.763926]], dtype=object)

In [109]:
DRUG_KNN_PREC = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
DRUG_KNN_PREC= pd.DataFrame({'Trial':DRUG_KNN_PREC.index, 'Accuracy':DRUG_KNN_PREC.values}).iloc[1:]
DRUG_KNN_PREC = DRUG_KNN_PREC.as_matrix(columns=DRUG_KNN_PREC.columns[1:])
DRUG_KNN_PREC

array([[0.875],
       [0.8339770000000001],
       [0.8610040000000001]], dtype=object)

In [121]:
DRUG_RF_PREC = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
DRUG_RF_PREC= pd.DataFrame({'Trial':DRUG_RF_PREC.index, 'Accuracy':DRUG_RF_PREC.values}).iloc[1:]
DRUG_RF_PREC = DRUG_RF_PREC.as_matrix(columns=DRUG_RF_PREC.columns[1:])
DRUG_RF_PREC

array([[0.8774700000000001],
       [0.826772],
       [0.83209]], dtype=object)

In [122]:
DRUG_LR_PREC = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
DRUG_LR_PREC= pd.DataFrame({'Trial':DRUG_LR_PREC.index, 'Accuracy':DRUG_LR_PREC.values}).iloc[1:]
DRUG_LR_PREC = DRUG_LR_PREC.as_matrix(columns=DRUG_LR_PREC.columns[1:])
DRUG_LR_PREC

array([[0.859316],
       [0.834615],
       [0.856618]], dtype=object)

In [123]:
DRUG_DT_PREC = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
DRUG_DT_PREC= pd.DataFrame({'Trial':DRUG_DT_PREC.index, 'Accuracy':DRUG_DT_PREC.values}).iloc[1:]
DRUG_DT_PREC = DRUG_DT_PREC.as_matrix(columns=DRUG_DT_PREC.columns[1:])
DRUG_DT_PREC

array([[0.867769],
       [0.823293],
       [0.860656]], dtype=object)

In [5]:
MUSH_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         1.000000          1.000000         1.000000   
1         RF         1.000000          1.000000         1.000000   
2         LR         0.971077          0.971975         0.967385   
3         DT         1.000000          1.000000         1.000000   

   trial2_precision  trial3_accuracy  trial3_precision  
0          1.000000         1.000000          1.000000  
1          1.000000         1.000000          1.000000  
2          0.968354         0.959385          0.952941  
3          1.000000         1.000000          1.000000

In [110]:
MUSH_KNN_ACC = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
MUSH_KNN_ACC= pd.DataFrame({'Trial':MUSH_KNN_ACC.index, 'Accuracy':MUSH_KNN_ACC.values}).iloc[1:]
MUSH_KNN_ACC = MUSH_KNN_ACC.as_matrix(columns=MUSH_KNN_ACC.columns[1:])
MUSH_KNN_ACC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

In [124]:
MUSH_RF_ACC = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
MUSH_RF_ACC= pd.DataFrame({'Trial':MUSH_RF_ACC.index, 'Accuracy':MUSH_RF_ACC.values}).iloc[1:]
MUSH_RF_ACC = MUSH_RF_ACC.as_matrix(columns=MUSH_RF_ACC.columns[1:])
MUSH_RF_ACC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

In [125]:
MUSH_LR_ACC = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
MUSH_LR_ACC= pd.DataFrame({'Trial':MUSH_LR_ACC.index, 'Accuracy':MUSH_LR_ACC.values}).iloc[1:]
MUSH_LR_ACC = MUSH_LR_ACC.as_matrix(columns=MUSH_LR_ACC.columns[1:])
MUSH_LR_ACC

array([[0.9710770000000001],
       [0.967385],
       [0.959385]], dtype=object)

In [126]:
MUSH_DT_ACC = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
MUSH_DT_ACC= pd.DataFrame({'Trial':MUSH_DT_ACC.index, 'Accuracy':MUSH_DT_ACC.values}).iloc[1:]
MUSH_DT_ACC = MUSH_DT_ACC.as_matrix(columns=MUSH_DT_ACC.columns[1:])
MUSH_DT_ACC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

In [127]:
MUSH_KNN_PREC = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
MUSH_KNN_PREC= pd.DataFrame({'Trial':MUSH_KNN_PREC.index, 'Accuracy':MUSH_KNN_PREC.values}).iloc[1:]
MUSH_KNN_PREC = MUSH_KNN_PREC.as_matrix(columns=MUSH_KNN_PREC.columns[1:])
MUSH_KNN_PREC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

In [128]:
MUSH_RF_PREC = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
MUSH_RF_PREC= pd.DataFrame({'Trial':MUSH_RF_PREC.index, 'Accuracy':MUSH_RF_PREC.values}).iloc[1:]
MUSH_RF_PREC = MUSH_RF_PREC.as_matrix(columns=MUSH_RF_PREC.columns[1:])
MUSH_RF_PREC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

In [129]:
MUSH_LR_PREC = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
MUSH_LR_PREC= pd.DataFrame({'Trial':MUSH_LR_PREC.index, 'Accuracy':MUSH_LR_PREC.values}).iloc[1:]
MUSH_LR_PREC = MUSH_LR_PREC.as_matrix(columns=MUSH_LR_PREC.columns[1:])
MUSH_LR_PREC

array([[0.971975],
       [0.968354],
       [0.952941]], dtype=object)

In [130]:
MUSH_DT_PREC = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
MUSH_DT_PREC= pd.DataFrame({'Trial':MUSH_DT_PREC.index, 'Accuracy':MUSH_DT_PREC.values}).iloc[1:]
MUSH_DT_PREC = MUSH_DT_PREC.as_matrix(columns=MUSH_DT_PREC.columns[1:])
MUSH_DT_PREC

array([[1.0],
       [1.0],
       [1.0]], dtype=object)

## Average train performances with optimal parameters in each dataset

In [6]:
HD_optimal_train_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.826701          0.824675         0.826361   
1         RF         0.818367          1.000000         0.830527   
2         LR         0.830867          0.812903         0.805612   
3         DT         0.735544          0.744048         0.813946   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.872180         0.789371          0.871212  
1          1.000000         0.814371          1.000000  
2          0.840278         0.814201          0.790850  
3          0.969925         0.698469          0.879195

In [7]:
DRUG_optimal_train_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.801045          0.857567         0.801058   
1         RF         0.810330          1.000000         0.803063   
2         LR         0.815621          0.855315         0.812992   
3         DT         0.786451          0.903418         0.693648   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.851533         0.803718          1.000000  
1          1.000000         0.807698          1.000000  
2          0.860153         0.811681          0.855186  
3          0.909357         0.687677          0.898356

In [8]:
MUSH_optimal_train_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.998923          1.000000         0.999231   
1         RF         1.000000          1.000000         1.000000   
2         LR         0.961993          0.961367         0.967995   
3         DT         0.998308          1.000000         1.000000   

   trial2_precision  trial3_accuracy  trial3_precision  
0           1.00000         0.998923           1.00000  
1           1.00000         1.000000           1.00000  
2           0.96829         0.964303           0.96308  
3           1.00000         0.995692           1.00000

## Average test performances with optimal parameters in each dataset

In [9]:
HD_optimal_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.786885          0.766667         0.819672   
1         RF         0.819672          0.846154         0.754098   
2         LR         0.803279          0.814815         0.786885   
3         DT         0.754098          0.705882         0.704918   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.875000         0.934426          0.937500  
1          0.777778         0.934426          0.937500  
2          0.805556         0.885246          0.857143  
3          0.766667         0.819672          0.878788

In [10]:
DRUG_optimal_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         0.777188          0.887097         0.827586   
1         RF         0.809019          0.884462         0.798408   
2         LR         0.801061          0.890688         0.822281   
3         DT         0.786451          0.928571         0.692308   

   trial2_precision  trial3_accuracy  trial3_precision  
0          0.857143         0.785146          0.862205  
1          0.827451         0.774536          0.828467  
2          0.863636         0.803714          0.874510  
3          0.904459         0.705570          0.947674

In [11]:
MUSH_optimal_test_df.head()

classifier  trial1_accuracy  trial1_precision  trial2_accuracy  \
0        KNN         1.000000          1.000000         1.000000   
1         RF         1.000000          1.000000         1.000000   
2         LR         0.969846          0.971903         0.966769   
3         DT         1.000000          1.000000         1.000000   

   trial2_precision  trial3_accuracy  trial3_precision  
0          1.000000         1.000000           1.00000  
1          1.000000         1.000000           1.00000  
2          0.968314         0.959385           0.95201  
3          1.000000         0.992615           1.00000

### Extract KNN accuracy and precision

In [12]:
HD_knn_accu = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
HD_knn_accu = pd.DataFrame({'Trial':HD_knn_accu.index, 'Accuracy':HD_knn_accu.values}).iloc[1:]
DRUG_knn_accu = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
DRUG_knn_accu = pd.DataFrame({'Trial':DRUG_knn_accu.index, 'Accuracy':DRUG_knn_accu.values}).iloc[1:]
MUSH_knn_accu = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
MUSH_knn_accu = pd.DataFrame({'Trial':MUSH_knn_accu.index, 'Accuracy':MUSH_knn_accu.values}).iloc[1:]
all_knn_accu = pd.concat([HD_knn_accu, DRUG_knn_accu, MUSH_knn_accu], ignore_index=True)
all_knn_accu = all_knn_accu.as_matrix(columns=all_knn_accu.columns[1:])
all_knn_accu

array([[0.7868850000000001],
       [0.770492],
       [0.8688520000000001],
       [0.795756],
       [0.8143239999999999],
       [0.793103],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [13]:
HD_optimal_test_knn_accu = HD_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
HD_optimal_test_knn_accu = pd.DataFrame({'Trial':HD_optimal_test_knn_accu.index, 'precision':HD_optimal_test_knn_accu.values}).iloc[1:]
DRUG_optimal_test_knn_accu = DRUG_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
DRUG_optimal_test_knn_accu = pd.DataFrame({'Trial':DRUG_optimal_test_knn_accu.index, 'precision':DRUG_optimal_test_knn_accu.values}).iloc[1:]
MUSH_optimal_test_knn_accu = MUSH_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
MUSH_optimal_test_knn_accu = pd.DataFrame({'Trial':MUSH_optimal_test_knn_accu.index, 'precision':MUSH_optimal_test_knn_accu.values}).iloc[1:]
all_optimal_test_knn_accu = pd.concat([HD_optimal_test_knn_accu, DRUG_optimal_test_knn_accu, MUSH_optimal_test_knn_accu],ignore_index=True)
all_optimal_test_knn_accu = all_optimal_test_knn_accu.as_matrix(columns=all_optimal_test_knn_accu.columns[1:])
all_optimal_test_knn_accu

array([[0.786885246],
       [0.819672],
       [0.934426],
       [0.777188329],
       [0.8275862070000001],
       [0.785145889],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [14]:
HD_knn_prec = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
HD_knn_prec = pd.DataFrame({'Trial':HD_knn_prec.index, 'precracy':HD_knn_prec.values}).iloc[1:]
DRUG_knn_prec = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
DRUG_knn_prec = pd.DataFrame({'Trial':DRUG_knn_prec.index, 'precracy':DRUG_knn_prec.values}).iloc[1:]
MUSH_knn_prec = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
MUSH_knn_prec = pd.DataFrame({'Trial':MUSH_knn_prec.index, 'precracy':MUSH_knn_prec.values}).iloc[1:]
all_knn_prec = pd.concat([HD_knn_prec, DRUG_knn_prec, MUSH_knn_prec], ignore_index=True)
all_knn_prec = all_knn_prec.as_matrix(columns=all_knn_prec.columns[1:])
all_knn_prec

array([[0.75],
       [0.8],
       [0.815789],
       [0.875],
       [0.8339770000000001],
       [0.8610040000000001],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [15]:
HD_optimal_test_knn_prec = HD_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
HD_optimal_test_knn_prec = pd.DataFrame({'Trial':HD_optimal_test_knn_prec.index, 'accuracy':HD_optimal_test_knn_prec.values}).iloc[1:]
DRUG_optimal_test_knn_prec = DRUG_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
DRUG_optimal_test_knn_prec = pd.DataFrame({'Trial':DRUG_optimal_test_knn_prec.index, 'accuracy':DRUG_optimal_test_knn_prec.values}).iloc[1:]
MUSH_optimal_test_knn_prec = MUSH_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
MUSH_optimal_test_knn_prec = pd.DataFrame({'Trial':MUSH_optimal_test_knn_prec.index, 'accuracy':MUSH_optimal_test_knn_prec.values}).iloc[1:]
all_optimal_test_knn_prec = pd.concat([HD_optimal_test_knn_prec, DRUG_optimal_test_knn_prec, MUSH_optimal_test_knn_prec],ignore_index=True)
all_optimal_test_knn_prec = all_optimal_test_knn_prec.as_matrix(columns=all_optimal_test_knn_prec.columns[1:])
all_optimal_test_knn_prec

array([[0.766667],
       [0.875],
       [0.9375],
       [0.8870967740000001],
       [0.857142857],
       [0.862204724],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [16]:
HD_optimal_train_knn_accu = HD_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
HD_optimal_train_knn_accu = pd.DataFrame({'Trial':HD_optimal_train_knn_accu.index, 'precision':HD_optimal_train_knn_accu.values}).iloc[1:]
DRUG_optimal_train_knn_accu = DRUG_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
DRUG_optimal_train_knn_accu = pd.DataFrame({'Trial':DRUG_optimal_train_knn_accu.index, 'precision':DRUG_optimal_train_knn_accu.values}).iloc[1:]
MUSH_optimal_train_knn_accu = MUSH_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[0]
MUSH_optimal_train_knn_accu = pd.DataFrame({'Trial':MUSH_optimal_train_knn_accu.index, 'precision':MUSH_optimal_train_knn_accu.values}).iloc[1:]
all_optimal_train_knn_accu = pd.concat([HD_optimal_train_knn_accu, DRUG_optimal_train_knn_accu, MUSH_optimal_train_knn_accu],ignore_index=True)
all_optimal_train_knn_accu = all_optimal_train_knn_accu.as_matrix(columns=all_optimal_train_knn_accu.columns[1:])
all_optimal_train_knn_accu

array([[0.826701],
       [0.826361],
       [0.789371],
       [0.801045],
       [0.801058],
       [0.803718],
       [0.998923],
       [0.999231],
       [0.998923]], dtype=object)

In [17]:
HD_optimal_train_knn_prec = HD_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
HD_optimal_train_knn_prec = pd.DataFrame({'Trial':HD_optimal_train_knn_prec.index, 'accuracy':HD_optimal_train_knn_prec.values}).iloc[1:]
DRUG_optimal_train_knn_prec = DRUG_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
DRUG_optimal_train_knn_prec = pd.DataFrame({'Trial':DRUG_optimal_train_knn_prec.index, 'accuracy':DRUG_optimal_train_knn_prec.values}).iloc[1:]
MUSH_optimal_train_knn_prec = MUSH_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[0]
MUSH_optimal_train_knn_prec = pd.DataFrame({'Trial':MUSH_optimal_train_knn_prec.index, 'accuracy':MUSH_optimal_train_knn_prec.values}).iloc[1:]
all_optimal_train_knn_prec = pd.concat([HD_optimal_train_knn_prec, DRUG_optimal_train_knn_prec, MUSH_optimal_train_knn_prec],ignore_index=True)
all_optimal_train_knn_prec = all_optimal_train_knn_prec.as_matrix(columns=all_optimal_train_knn_prec.columns[1:])
all_optimal_train_knn_prec

array([[0.824675],
       [0.87218],
       [0.8712120000000001],
       [0.857567],
       [0.851533],
       [1.0],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

### Extract RF accuracy and precision

In [18]:
HD_RF_accu = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
HD_RF_accu = pd.DataFrame({'Trial':HD_RF_accu.index, 'Accuracy':HD_RF_accu.values}).iloc[1:]
DRUG_RF_accu = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
DRUG_RF_accu = pd.DataFrame({'Trial':DRUG_RF_accu.index, 'Accuracy':DRUG_RF_accu.values}).iloc[1:]
MUSH_RF_accu = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
MUSH_RF_accu = pd.DataFrame({'Trial':MUSH_RF_accu.index, 'Accuracy':MUSH_RF_accu.values}).iloc[1:]
all_RF_accu = pd.concat([HD_RF_accu, DRUG_RF_accu, MUSH_RF_accu], ignore_index=True)
all_RF_accu = all_RF_accu.as_matrix(columns=all_RF_accu.columns[1:])
all_RF_accu

array([[0.803279],
       [0.7540979999999999],
       [0.934426],
       [0.8010609999999999],
       [0.795756],
       [0.777188],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [19]:
HD_optimal_test_RF_accu = HD_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
HD_optimal_test_RF_accu = pd.DataFrame({'Trial':HD_optimal_test_RF_accu.index, 'precision':HD_optimal_test_RF_accu.values}).iloc[1:]
DRUG_optimal_test_RF_accu = DRUG_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
DRUG_optimal_test_RF_accu = pd.DataFrame({'Trial':DRUG_optimal_test_RF_accu.index, 'precision':DRUG_optimal_test_RF_accu.values}).iloc[1:]
MUSH_optimal_test_RF_accu = MUSH_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
MUSH_optimal_test_RF_accu = pd.DataFrame({'Trial':MUSH_optimal_test_RF_accu.index, 'precision':MUSH_optimal_test_RF_accu.values}).iloc[1:]
all_optimal_test_RF_accu = pd.concat([HD_optimal_test_RF_accu, DRUG_optimal_test_RF_accu, MUSH_optimal_test_RF_accu],ignore_index=True)
all_optimal_test_RF_accu = all_optimal_test_RF_accu.as_matrix(columns=all_optimal_test_RF_accu.columns[1:])
all_optimal_test_RF_accu

array([[0.8196721309999999],
       [0.7540979999999999],
       [0.934426],
       [0.8090185679999999],
       [0.798408488],
       [0.7745358090000001],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [20]:
HD_RF_prec = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
HD_RF_prec = pd.DataFrame({'Trial':HD_RF_prec.index, 'precracy':HD_RF_prec.values}).iloc[1:]
DRUG_RF_prec = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
DRUG_RF_prec = pd.DataFrame({'Trial':DRUG_RF_prec.index, 'precracy':DRUG_RF_prec.values}).iloc[1:]
MUSH_RF_prec = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
MUSH_RF_prec = pd.DataFrame({'Trial':MUSH_RF_prec.index, 'precracy':MUSH_RF_prec.values}).iloc[1:]
all_RF_prec = pd.concat([HD_RF_prec, DRUG_RF_prec, MUSH_RF_prec], ignore_index=True)
all_RF_prec = all_RF_prec.as_matrix(columns=all_RF_prec.columns[1:])
all_RF_prec

array([[0.814815],
       [0.783784],
       [0.966667],
       [0.8774700000000001],
       [0.826772],
       [0.83209],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [21]:
HD_optimal_test_RF_prec = HD_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
HD_optimal_test_RF_prec = pd.DataFrame({'Trial':HD_optimal_test_RF_prec.index, 'accuracy':HD_optimal_test_RF_prec.values}).iloc[1:]
DRUG_optimal_test_RF_prec = DRUG_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
DRUG_optimal_test_RF_prec = pd.DataFrame({'Trial':DRUG_optimal_test_RF_prec.index, 'accuracy':DRUG_optimal_test_RF_prec.values}).iloc[1:]
MUSH_optimal_test_RF_prec = MUSH_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
MUSH_optimal_test_RF_prec = pd.DataFrame({'Trial':MUSH_optimal_test_RF_prec.index, 'accuracy':MUSH_optimal_test_RF_prec.values}).iloc[1:]
all_optimal_test_RF_prec = pd.concat([HD_optimal_test_RF_prec, DRUG_optimal_test_RF_prec, MUSH_optimal_test_RF_prec],ignore_index=True)
all_optimal_test_RF_prec = all_optimal_test_RF_prec.as_matrix(columns=all_optimal_test_RF_prec.columns[1:])
all_optimal_test_RF_prec

array([[0.8461540000000001],
       [0.777778],
       [0.9375],
       [0.8844621509999999],
       [0.82745098],
       [0.828467153],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [22]:
HD_optimal_train_RF_accu = HD_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
HD_optimal_train_RF_accu = pd.DataFrame({'Trial':HD_optimal_train_RF_accu.index, 'precision':HD_optimal_train_RF_accu.values}).iloc[1:]
DRUG_optimal_train_RF_accu = DRUG_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
DRUG_optimal_train_RF_accu = pd.DataFrame({'Trial':DRUG_optimal_train_RF_accu.index, 'precision':DRUG_optimal_train_RF_accu.values}).iloc[1:]
MUSH_optimal_train_RF_accu = MUSH_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[1]
MUSH_optimal_train_RF_accu = pd.DataFrame({'Trial':MUSH_optimal_train_RF_accu.index, 'precision':MUSH_optimal_train_RF_accu.values}).iloc[1:]
all_optimal_train_RF_accu = pd.concat([HD_optimal_train_RF_accu, DRUG_optimal_train_RF_accu, MUSH_optimal_train_RF_accu],ignore_index=True)
all_optimal_train_RF_accu = all_optimal_train_RF_accu.as_matrix(columns=all_optimal_train_RF_accu.columns[1:])
all_optimal_train_RF_accu

array([[0.818367],
       [0.830527],
       [0.814371],
       [0.81033],
       [0.803063],
       [0.8076979999999999],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [23]:
HD_optimal_train_RF_prec = HD_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
HD_optimal_train_RF_prec = pd.DataFrame({'Trial':HD_optimal_train_RF_prec.index, 'accuracy':HD_optimal_train_RF_prec.values}).iloc[1:]
DRUG_optimal_train_RF_prec = DRUG_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
DRUG_optimal_train_RF_prec = pd.DataFrame({'Trial':DRUG_optimal_train_RF_prec.index, 'accuracy':DRUG_optimal_train_RF_prec.values}).iloc[1:]
MUSH_optimal_train_RF_prec = MUSH_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[1]
MUSH_optimal_train_RF_prec = pd.DataFrame({'Trial':MUSH_optimal_train_RF_prec.index, 'accuracy':MUSH_optimal_train_RF_prec.values}).iloc[1:]
all_optimal_train_RF_prec = pd.concat([HD_optimal_train_RF_prec, DRUG_optimal_train_RF_prec, MUSH_optimal_train_RF_prec],ignore_index=True)
all_optimal_train_RF_prec = all_optimal_train_RF_prec.as_matrix(columns=all_optimal_train_RF_prec.columns[1:])
all_optimal_train_RF_prec

array([[1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

### Extract LR accuracy and precision

In [24]:
HD_LR_accu = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
HD_LR_accu = pd.DataFrame({'Trial':HD_LR_accu.index, 'Accuracy':HD_LR_accu.values}).iloc[1:]
DRUG_LR_accu = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
DRUG_LR_accu = pd.DataFrame({'Trial':DRUG_LR_accu.index, 'Accuracy':DRUG_LR_accu.values}).iloc[1:]
MUSH_LR_accu = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
MUSH_LR_accu = pd.DataFrame({'Trial':MUSH_LR_accu.index, 'Accuracy':MUSH_LR_accu.values}).iloc[1:]
all_LR_accu = pd.concat([HD_LR_accu, DRUG_LR_accu, MUSH_LR_accu], ignore_index=True)
all_LR_accu = all_LR_accu.as_matrix(columns=all_LR_accu.columns[1:])
all_LR_accu

array([[0.803279],
       [0.819672],
       [0.918033],
       [0.803714],
       [0.816976],
       [0.811671],
       [0.9710770000000001],
       [0.967385],
       [0.959385]], dtype=object)

In [25]:
HD_optimal_test_LR_accu = HD_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
HD_optimal_test_LR_accu = pd.DataFrame({'Trial':HD_optimal_test_LR_accu.index, 'precision':HD_optimal_test_LR_accu.values}).iloc[1:]
DRUG_optimal_test_LR_accu = DRUG_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
DRUG_optimal_test_LR_accu = pd.DataFrame({'Trial':DRUG_optimal_test_LR_accu.index, 'precision':DRUG_optimal_test_LR_accu.values}).iloc[1:]
MUSH_optimal_test_LR_accu = MUSH_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
MUSH_optimal_test_LR_accu = pd.DataFrame({'Trial':MUSH_optimal_test_LR_accu.index, 'precision':MUSH_optimal_test_LR_accu.values}).iloc[1:]
all_optimal_test_LR_accu = pd.concat([HD_optimal_test_LR_accu, DRUG_optimal_test_LR_accu, MUSH_optimal_test_LR_accu],ignore_index=True)
all_optimal_test_LR_accu = all_optimal_test_LR_accu.as_matrix(columns=all_optimal_test_LR_accu.columns[1:])
all_optimal_test_LR_accu

array([[0.8032786890000001],
       [0.7868850000000001],
       [0.8852459999999999],
       [0.801061008],
       [0.822281167],
       [0.803713528],
       [0.9698459999999999],
       [0.9667690000000001],
       [0.959385]], dtype=object)

In [26]:
HD_LR_prec = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
HD_LR_prec = pd.DataFrame({'Trial':HD_LR_prec.index, 'precracy':HD_LR_prec.values}).iloc[1:]
DRUG_LR_prec = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
DRUG_LR_prec = pd.DataFrame({'Trial':DRUG_LR_prec.index, 'precracy':DRUG_LR_prec.values}).iloc[1:]
MUSH_LR_prec = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
MUSH_LR_prec = pd.DataFrame({'Trial':MUSH_LR_prec.index, 'precracy':MUSH_LR_prec.values}).iloc[1:]
all_LR_prec = pd.concat([HD_LR_prec, DRUG_LR_prec, MUSH_LR_prec], ignore_index=True)
all_LR_prec = all_LR_prec.as_matrix(columns=all_LR_prec.columns[1:])
all_LR_prec

array([[0.793103],
       [0.815789],
       [0.909091],
       [0.859316],
       [0.834615],
       [0.856618],
       [0.971975],
       [0.968354],
       [0.952941]], dtype=object)

In [27]:
HD_optimal_test_LR_prec = HD_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
HD_optimal_test_LR_prec = pd.DataFrame({'Trial':HD_optimal_test_LR_prec.index, 'accuracy':HD_optimal_test_LR_prec.values}).iloc[1:]
DRUG_optimal_test_LR_prec = DRUG_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
DRUG_optimal_test_LR_prec = pd.DataFrame({'Trial':DRUG_optimal_test_LR_prec.index, 'accuracy':DRUG_optimal_test_LR_prec.values}).iloc[1:]
MUSH_optimal_test_LR_prec = MUSH_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
MUSH_optimal_test_LR_prec = pd.DataFrame({'Trial':MUSH_optimal_test_LR_prec.index, 'accuracy':MUSH_optimal_test_LR_prec.values}).iloc[1:]
all_optimal_test_LR_prec = pd.concat([HD_optimal_test_LR_prec, DRUG_optimal_test_LR_prec, MUSH_optimal_test_LR_prec],ignore_index=True)
all_optimal_test_LR_prec = all_optimal_test_LR_prec.as_matrix(columns=all_optimal_test_LR_prec.columns[1:])
all_optimal_test_LR_prec

array([[0.814815],
       [0.805556],
       [0.857143],
       [0.890688259],
       [0.8636363640000001],
       [0.8745098040000001],
       [0.9719030000000001],
       [0.9683139999999999],
       [0.95201]], dtype=object)

In [28]:
HD_optimal_train_LR_accu = HD_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
HD_optimal_train_LR_accu = pd.DataFrame({'Trial':HD_optimal_train_LR_accu.index, 'precision':HD_optimal_train_LR_accu.values}).iloc[1:]
DRUG_optimal_train_LR_accu = DRUG_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
DRUG_optimal_train_LR_accu = pd.DataFrame({'Trial':DRUG_optimal_train_LR_accu.index, 'precision':DRUG_optimal_train_LR_accu.values}).iloc[1:]
MUSH_optimal_train_LR_accu = MUSH_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[2]
MUSH_optimal_train_LR_accu = pd.DataFrame({'Trial':MUSH_optimal_train_LR_accu.index, 'precision':MUSH_optimal_train_LR_accu.values}).iloc[1:]
all_optimal_train_LR_accu = pd.concat([HD_optimal_train_LR_accu, DRUG_optimal_train_LR_accu, MUSH_optimal_train_LR_accu],ignore_index=True)
all_optimal_train_LR_accu = all_optimal_train_LR_accu.as_matrix(columns=all_optimal_train_LR_accu.columns[1:])
all_optimal_train_LR_accu

array([[0.830867],
       [0.805612],
       [0.8142010000000001],
       [0.815621],
       [0.812992],
       [0.811681],
       [0.961993],
       [0.967995],
       [0.964303]], dtype=object)

In [29]:
HD_optimal_train_LR_prec = HD_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
HD_optimal_train_LR_prec = pd.DataFrame({'Trial':HD_optimal_train_LR_prec.index, 'accuracy':HD_optimal_train_LR_prec.values}).iloc[1:]
DRUG_optimal_train_LR_prec = DRUG_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
DRUG_optimal_train_LR_prec = pd.DataFrame({'Trial':DRUG_optimal_train_LR_prec.index, 'accuracy':DRUG_optimal_train_LR_prec.values}).iloc[1:]
MUSH_optimal_train_LR_prec = MUSH_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[2]
MUSH_optimal_train_LR_prec = pd.DataFrame({'Trial':MUSH_optimal_train_LR_prec.index, 'accuracy':MUSH_optimal_train_LR_prec.values}).iloc[1:]
all_optimal_train_LR_prec = pd.concat([HD_optimal_train_LR_prec, DRUG_optimal_train_LR_prec, MUSH_optimal_train_LR_prec],ignore_index=True)
all_optimal_train_LR_prec = all_optimal_train_LR_prec.as_matrix(columns=all_optimal_train_LR_prec.columns[1:])
all_optimal_train_LR_prec

array([[0.8129029999999999],
       [0.8402780000000001],
       [0.79085],
       [0.8553149999999999],
       [0.8601530000000001],
       [0.8551860000000001],
       [0.961367],
       [0.96829],
       [0.9630799999999999]], dtype=object)

### Extract DT accuracy and precision

In [30]:
HD_DT_accu = HD_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
HD_DT_accu = pd.DataFrame({'Trial':HD_DT_accu.index, 'Accuracy':HD_DT_accu.values}).iloc[1:]
DRUG_DT_accu = DRUG_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
DRUG_DT_accu = pd.DataFrame({'Trial':DRUG_DT_accu.index, 'Accuracy':DRUG_DT_accu.values}).iloc[1:]
MUSH_DT_accu = MUSH_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
MUSH_DT_accu = pd.DataFrame({'Trial':MUSH_DT_accu.index, 'Accuracy':MUSH_DT_accu.values}).iloc[1:]
all_DT_accu = pd.concat([HD_DT_accu, DRUG_DT_accu, MUSH_DT_accu], ignore_index=True)
all_DT_accu = all_DT_accu.as_matrix(columns=all_DT_accu.columns[1:])
all_DT_accu

array([[0.770492],
       [0.7213109999999999],
       [0.852459],
       [0.774536],
       [0.782493],
       [0.763926],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [31]:
HD_optimal_test_DT_accu = HD_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
HD_optimal_test_DT_accu = pd.DataFrame({'Trial':HD_optimal_test_DT_accu.index, 'precision':HD_optimal_test_DT_accu.values}).iloc[1:]
DRUG_optimal_test_DT_accu = DRUG_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
DRUG_optimal_test_DT_accu = pd.DataFrame({'Trial':DRUG_optimal_test_DT_accu.index, 'precision':DRUG_optimal_test_DT_accu.values}).iloc[1:]
MUSH_optimal_test_DT_accu = MUSH_optimal_test_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
MUSH_optimal_test_DT_accu = pd.DataFrame({'Trial':MUSH_optimal_test_DT_accu.index, 'precision':MUSH_optimal_test_DT_accu.values}).iloc[1:]
all_optimal_test_DT_accu = pd.concat([HD_optimal_test_DT_accu, DRUG_optimal_test_DT_accu, MUSH_optimal_test_DT_accu],ignore_index=True)
all_optimal_test_DT_accu = all_optimal_test_DT_accu.as_matrix(columns=all_optimal_test_DT_accu.columns[1:])
all_optimal_test_DT_accu 

array([[0.7540979999999999],
       [0.704918],
       [0.819672],
       [0.786451343],
       [0.692307692],
       [0.705570292],
       [1.0],
       [1.0],
       [0.9926149999999999]], dtype=object)

In [32]:
HD_DT_prec = HD_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
HD_DT_prec = pd.DataFrame({'Trial':HD_DT_prec.index, 'precracy':HD_DT_prec.values}).iloc[1:]
DRUG_DT_prec = DRUG_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
DRUG_DT_prec = pd.DataFrame({'Trial':DRUG_DT_prec.index, 'precracy':DRUG_DT_prec.values}).iloc[1:]
MUSH_DT_prec = MUSH_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
MUSH_DT_prec = pd.DataFrame({'Trial':MUSH_DT_prec.index, 'precracy':MUSH_DT_prec.values}).iloc[1:]
all_DT_prec = pd.concat([HD_DT_prec, DRUG_DT_prec, MUSH_DT_prec], ignore_index=True)
all_DT_prec = all_DT_prec.as_matrix(columns=all_DT_prec.columns[1:])
all_DT_prec

array([[0.758621],
       [0.74359],
       [0.8787879999999999],
       [0.867769],
       [0.823293],
       [0.860656],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [33]:
HD_optimal_test_DT_prec = HD_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
HD_optimal_test_DT_prec = pd.DataFrame({'Trial':HD_optimal_test_DT_prec.index, 'accuracy':HD_optimal_test_DT_prec.values}).iloc[1:]
DRUG_optimal_test_DT_prec = DRUG_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
DRUG_optimal_test_DT_prec = pd.DataFrame({'Trial':DRUG_optimal_test_DT_prec.index, 'accuracy':DRUG_optimal_test_DT_prec.values}).iloc[1:]
MUSH_optimal_test_DT_prec = MUSH_optimal_test_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
MUSH_optimal_test_DT_prec = pd.DataFrame({'Trial':MUSH_optimal_test_DT_prec.index, 'accuracy':MUSH_optimal_test_DT_prec.values}).iloc[1:]
all_optimal_test_DT_prec = pd.concat([HD_optimal_test_DT_prec, DRUG_optimal_test_DT_prec, MUSH_optimal_test_DT_prec],ignore_index=True)
all_optimal_test_DT_prec = all_optimal_test_DT_prec.as_matrix(columns=all_optimal_test_DT_prec.columns[1:])
all_optimal_test_DT_prec

array([[0.705882],
       [0.766667],
       [0.8787879999999999],
       [0.9285714290000001],
       [0.904458599],
       [0.947674419],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [34]:
HD_optimal_train_DT_accu = HD_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
HD_optimal_train_DT_accu = pd.DataFrame({'Trial':HD_optimal_train_DT_accu.index, 'precision':HD_optimal_train_DT_accu.values}).iloc[1:]
DRUG_optimal_train_DT_accu = DRUG_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
DRUG_optimal_train_DT_accu = pd.DataFrame({'Trial':DRUG_optimal_train_DT_accu.index, 'precision':DRUG_optimal_train_DT_accu.values}).iloc[1:]
MUSH_optimal_train_DT_accu = MUSH_optimal_train_df.drop(['trial1_precision','trial2_precision','trial3_precision'],axis=1).loc[3]
MUSH_optimal_train_DT_accu = pd.DataFrame({'Trial':MUSH_optimal_train_DT_accu.index, 'precision':MUSH_optimal_train_DT_accu.values}).iloc[1:]
all_optimal_train_DT_accu = pd.concat([HD_optimal_train_DT_accu, DRUG_optimal_train_DT_accu, MUSH_optimal_train_DT_accu],ignore_index=True)
all_optimal_train_DT_accu = all_optimal_train_DT_accu.as_matrix(columns=all_optimal_train_DT_accu.columns[1:])
all_optimal_train_DT_accu 

array([[0.735544],
       [0.8139460000000001],
       [0.698469],
       [0.786451],
       [0.6936479999999999],
       [0.6876770000000001],
       [0.998308],
       [1.0],
       [0.995692]], dtype=object)

In [35]:
HD_optimal_train_DT_prec = HD_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
HD_optimal_train_DT_prec = pd.DataFrame({'Trial':HD_optimal_train_DT_prec.index, 'accuracy':HD_optimal_train_DT_prec.values}).iloc[1:]
DRUG_optimal_train_DT_prec = DRUG_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
DRUG_optimal_train_DT_prec = pd.DataFrame({'Trial':DRUG_optimal_train_DT_prec.index, 'accuracy':DRUG_optimal_train_DT_prec.values}).iloc[1:]
MUSH_optimal_train_DT_prec = MUSH_optimal_train_df.drop(['trial1_accuracy','trial2_accuracy','trial3_accuracy'],axis=1).loc[3]
MUSH_optimal_train_DT_prec = pd.DataFrame({'Trial':MUSH_optimal_train_DT_prec.index, 'accuracy':MUSH_optimal_train_DT_prec.values}).iloc[1:]
all_optimal_train_DT_prec = pd.concat([HD_optimal_train_DT_prec, DRUG_optimal_train_DT_prec, MUSH_optimal_train_DT_prec],ignore_index=True)
all_optimal_train_DT_prec = all_optimal_train_DT_prec.as_matrix(columns=all_optimal_train_DT_prec.columns[1:])
all_optimal_train_DT_prec

array([[0.7440479999999999],
       [0.969925],
       [0.8791950000000001],
       [0.903418],
       [0.909357],
       [0.8983559999999999],
       [1.0],
       [1.0],
       [1.0]], dtype=object)

In [37]:
print('Mean KNN Test Accuracy',all_knn_accu.mean())
print(' ')
print('Mean Optimal Train KNN Accuracy',all_optimal_train_knn_accu.mean())
print(' ')
print('Mean Optimal Test KNN Accuracy',all_optimal_test_knn_accu.mean())
print(' ')
print('Mean KNN Test Precision',all_knn_prec.mean())
print(' ')
print('Mean Optimal Train KNN Precision',all_optimal_train_knn_prec.mean())
print(' ')
print('Mean Optimal Test KNN Precision',all_optimal_test_knn_prec.mean())
print(' ')
print('Mean RF Test Accuracy',all_RF_accu.mean())
print(' ')
print('Mean RF Optimal Train Accuracy',all_optimal_train_RF_accu.mean())
print(' ')
print('Mean RF Optimal Test Accuracy',all_optimal_test_RF_accu.mean())
print(' ')
print('Mean RF Test Precision',all_RF_prec.mean())
print(' ')
print('Mean RF Optimal Train Precision',all_optimal_train_RF_prec.mean())
print(' ')
print('Mean RF Optimal Test Precision',all_optimal_test_RF_prec.mean())
print(' ')
print('Mean LR Test Accuracy',all_LR_accu.mean())
print(' ')
print('Mean LR Optimal Train Accuracy',all_optimal_train_LR_accu.mean())
print(' ')
print('Mean LR Optimal Test Accuracy',all_optimal_test_LR_accu.mean())
print(' ')
print('Mean LR Test Precision',all_LR_prec.mean())
print(' ')
print('Mean LR Optimal Train Precision',all_optimal_train_LR_prec.mean())
print(' ')
print('Mean LR Optimal Test Precision',all_optimal_test_LR_prec.mean())
print(' ')
print('Mean DT Test Accuracy',all_DT_accu.mean())
print(' ')
print('Mean DT Optimal Train  Accuracy',all_optimal_train_DT_accu.mean())
print(' ')
print('Mean DT Optimal Test  Accuracy',all_optimal_test_DT_accu.mean())
print(' ')
print('Mean DT Test Precision',all_DT_prec.mean())
print(' ')
print('Mean DT Optimal Train Precision',all_optimal_train_DT_prec.mean())
print(' ')
print('Mean DT Optimal Test Precision',all_optimal_test_DT_prec.mean())

Mean KNN Test Accuracy 0.8699346666666667
 
Mean Optimal Train KNN Accuracy 0.8717034444444445
 
Mean Optimal Test KNN Accuracy 0.8812115189999999
 
Mean KNN Test Precision 0.8817522222222223
 
Mean Optimal Train KNN Precision 0.9196852222222223
 
Mean Optimal Test KNN Precision 0.9095123727777776
 
Mean RF Test Accuracy 0.8739786666666666
 
Mean RF Optimal Train Accuracy 0.8760395555555556
 
Mean RF Optimal Test Accuracy 0.8766843328888889
 
Mean RF Test Precision 0.9001775555555555
 
Mean RF Optimal Train Precision 1.0
 
Mean RF Optimal Test Precision 0.900201364888889
 
Mean LR Test Accuracy 0.874576888888889
 
Mean LR Optimal Train Accuracy 0.8650294444444445
 
Mean LR Optimal Test Accuracy 0.8664961546666667
 
Mean LR Test Precision 0.8846446666666666
 
Mean LR Optimal Train Precision 0.8786024444444444
 
Mean LR Optimal Test Precision 0.8887306030000001
 
Mean DT Test Accuracy 0.8516907777777778
 
Mean DT Optimal Train  Accuracy 0.8233038888888888
 
Mean DT Optimal Test  Accuracy

In [38]:
print('std KNN Test Accuracy',all_knn_accu.std())
print(' ')
print('std Optimal Train KNN Accuracy',all_optimal_train_knn_accu.std())
print(' ')
print('std Optimal Test KNN Accuracy',all_optimal_test_knn_accu.std())
print(' ')
print('std KNN Test Precision',all_knn_prec.std())
print(' ')
print('std Optimal Train KNN Precision',all_optimal_train_knn_prec.std())
print(' ')
print('std Optimal Test KNN Precision',all_optimal_test_knn_prec.std())
print(' ')
print('std RF Test Accuracy',all_RF_accu.std())
print(' ')
print('std RF Optimal Train Accuracy',all_optimal_train_RF_accu.std())
print(' ')
print('std RF Optimal Test Accuracy',all_optimal_test_RF_accu.std())
print(' ')
print('std RF Test Precision',all_RF_prec.std())
print(' ')
print('std RF Optimal Train Precision',all_optimal_train_RF_prec.std())
print(' ')
print('std RF Optimal Test Precision',all_optimal_test_RF_prec.std())
print(' ')
print('std LR Test Accuracy',all_LR_accu.std())
print(' ')
print('std LR Optimal Train Accuracy',all_optimal_train_LR_accu.std())
print(' ')
print('std LR Optimal Test Accuracy',all_optimal_test_LR_accu.std())
print(' ')
print('std LR Test Precision',all_LR_prec.std())
print(' ')
print('std LR Optimal Train Precision',all_optimal_train_LR_prec.std())
print(' ')
print('std LR Optimal Test Precision',all_optimal_test_LR_prec.std())
print(' ')
print('std DT Test Accuracy',all_DT_accu.std())
print(' ')
print('std DT Optimal Train  Accuracy',all_optimal_train_DT_accu.std())
print(' ')
print('std DT Optimal Test  Accuracy',all_optimal_test_DT_accu.std())
print(' ')
print('std DT Test Precision',all_DT_prec.std())
print(' ')
print('std DT Optimal Train Precision',all_optimal_train_DT_prec.std())
print(' ')
print('std DT Optimal Test Precision',all_optimal_test_DT_prec.std())

std KNN Test Accuracy 0.09547330161882955
 
std Optimal Train KNN Accuracy 0.09073656128731632
 
std Optimal Test KNN Accuracy 0.09473562760062204
 
std KNN Test Precision 0.09012299282496333
 
std Optimal Train KNN Precision 0.07298294685256242
 
std Optimal Test KNN Precision 0.0763226212290629
 
std RF Test Accuracy 0.10081447836165863
 
std RF Optimal Train Accuracy 0.08794758164208587
 
std RF Optimal Test Accuracy 0.09909156603031198
 
std RF Test Precision 0.0854325965764969
 
std RF Optimal Train Precision 0.0
 
std RF Optimal Test Precision 0.08155790534887626
 
std LR Test Accuracy 0.07257254171508434
 
std LR Optimal Train Accuracy 0.07081686724708569
 
std LR Optimal Test Accuracy 0.07470571449698413
 
std LR Test Precision 0.06407186458449086
 
std LR Optimal Train Precision 0.064071986562184
 
std LR Optimal Test Precision 0.059133125490068314
 
std DT Test Accuracy 0.10955639984427888
 
std DT Optimal Train  Accuracy 0.12974426599999148
 
std DT Optimal Test  Accuracy 0.

# T-Tests + Cohen's 

In [73]:
from scipy import stats
from numpy import std, mean, sqrt

In [67]:
#correct if the population S.D. is expected to be equal for the two groups.
def cohen_d(x,y):
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    return (mean(x) - mean(y)) / sqrt(((nx-1)*std(x, ddof=1) ** 2 + (ny-1)*std(y, ddof=1) ** 2) / dof)

## 3 Trials x 3 Datasets

### KNN vs RF: Accuracy

In [80]:
KNN_RF_accu = stats.ttest_ind(all_knn_accu, all_RF_accu, axis=None, equal_var=False)
KNN_RF_accu

Ttest_indResult(statistic=-0.08237912049829567, pvalue=0.9353700164759006)

In [72]:
print('cohens dvalue=',cohen_d(all_RF_accu, all_knn_accu))

cohens dvalue= 0.03883388982168574


### KNN vs RF: Precision

In [49]:
KNN_RF_prec = stats.ttest_ind(all_knn_prec, all_RF_prec, axis=None, equal_var=False)
KNN_RF_prec

Ttest_indResult(statistic=-0.41966788328071103, pvalue=0.6803247491130351)

In [74]:
print('cohens dvalue=',cohen_d(all_RF_prec, all_knn_prec))

cohens dvalue= 0.1978333374093302


### KNN vs LR: Accuracy

In [50]:
KNN_LR_accu = stats.ttest_ind(all_knn_accu, all_LR_accu, axis=None, equal_var=False)
KNN_LR_accu

Ttest_indResult(statistic=-0.10948696264796162, pvalue=0.9142742345641675)

In [75]:
print('cohens dvalue=',cohen_d(all_LR_accu, all_knn_accu))

cohens dvalue= 0.05161264915992793


### KNN vs LR: Precision

In [51]:
KNN_LR_prec = stats.ttest_ind(all_knn_prec, all_LR_prec, axis=None, equal_var=False)
KNN_LR_prec

Ttest_indResult(statistic=-0.0739850056992834, pvalue=0.942037368252181)

In [81]:
print('cohens dvalue=',cohen_d(all_LR_prec, all_knn_prec))

cohens dvalue= 0.03487686615739244


### KNN vs DT: Accuracy

In [52]:
KNN_DT_accu = stats.ttest_ind(all_knn_accu, all_DT_accu, axis=None, equal_var=False)
KNN_DT_accu

Ttest_indResult(statistic=0.35509007001735093, pvalue=0.7272454847876506)

In [83]:
print('cohens dvalue=',cohen_d(all_knn_accu, all_DT_accu))

cohens dvalue= 0.16739106429418318


### KNN vs DT: Precision

In [53]:
KNN_DT_prec = stats.ttest_ind(all_knn_prec, all_DT_prec, axis=None, equal_var=False)
KNN_DT_prec

Ttest_indResult(statistic=0.007350051447786862, pvalue=0.9942266212111703)

In [84]:
print('cohens dvalue=',cohen_d(all_knn_prec, all_DT_prec))

cohens dvalue= 0.0034648474805333944


### RF vs DT: Accuracy

In [54]:
RF_DT_accu = stats.ttest_ind(all_RF_accu, all_DT_accu, axis=None, equal_var=False)
RF_DT_accu

Ttest_indResult(statistic=0.4234173584991528, pvalue=0.6776660331399336)

In [85]:
print('cohens dvalue=',cohen_d(all_RF_accu, all_DT_accu))

cohens dvalue= 0.1996008569778976


### RF vs DT: Precision

In [55]:
RF_DT_prec = stats.ttest_ind(all_RF_prec, all_DT_prec, axis=None, equal_var=False)
RF_DT_prec

Ttest_indResult(statistic=0.41677282060327353, pvalue=0.6824370467864864)

In [86]:
print('cohens dvalue=',cohen_d(all_RF_prec, all_DT_prec))

cohens dvalue= 0.19646859177521278


### LR vs DT: Accuracy

In [234]:
LR_DT_accu = stats.ttest_ind(all_LR_accu, all_DT_accu, axis=None, equal_var=False)
LR_DT_accu

Ttest_indResult(statistic=0.49258211683174746, pvalue=0.6300042295775338)

In [87]:
print('cohens dvalue=',cohen_d(all_LR_accu, all_DT_accu))

cohens dvalue= 0.2322054367353019


### LR vs DT: Precision

In [57]:
LR_DT_prec = stats.ttest_ind(all_LR_prec, all_DT_prec, axis=None, equal_var=False, nan_policy='propagate')
LR_DT_prec

Ttest_indResult(statistic=0.08009581321712511, pvalue=0.937288580439398)

In [90]:
print('cohens dvalue=',cohen_d(all_LR_prec, all_DT_prec))

cohens dvalue= 0.03775752844698684


### LR vs RF: Accuracy

In [58]:
LR_RF_accu = stats.ttest_ind(all_LR_accu, all_RF_accu, axis=None, equal_var=False, nan_policy='propagate')
LR_RF_accu

Ttest_indResult(statistic=0.013621341710561468, pvalue=0.9893172712345649)

In [91]:
print('cohens dvalue=',cohen_d(all_LR_accu, all_RF_accu))

cohens dvalue= 0.006421162061598121


### LR vs RF: Precision

In [59]:
LR_RF_prec = stats.ttest_ind(all_LR_prec, all_RF_prec, axis=None, equal_var=False, nan_policy='propagate')
LR_RF_prec

Ttest_indResult(statistic=-0.41140532836191834, pvalue=0.686656781861832)

In [93]:
print('cohens dvalue=',cohen_d(all_RF_prec, all_LR_prec))

cohens dvalue= 0.19393833166732719


In [135]:
print('HD: Mean KNN Test Accuracy', HD_KNN_ACC.mean())
print('HD: Mean RF Test Accuracy',HD_RF_ACC.mean())
print('HD: Mean LR Test Accuracy',HD_LR_ACC.mean())
print('HD: Mean DT Test Accuracy',HD_DT_ACC.mean())
print('HD: Mean KNN Test Precision',HD_KNN_PREC.mean())
print('HD: Mean RF Test Precision',HD_RF_PREC.mean())
print('HD: Mean LR Test Precision',HD_LR_PREC.mean())
print('HD: Mean DT Test Precision',HD_DT_PREC.mean())

HD: Mean KNN Test Accuracy 0.8087430000000001
HD: Mean RF Test Accuracy 0.830601
HD: Mean LR Test Accuracy 0.8469946666666667
HD: Mean DT Test Accuracy 0.7814206666666667
HD: Mean KNN Test Precision 0.7885963333333333
HD: Mean RF Test Precision 0.8550886666666667
HD: Mean LR Test Precision 0.8393276666666667
HD: Mean DT Test Precision 0.7936663333333334


In [137]:
print('DRUG: Mean KNN Test Accuracy',DRUG_KNN_ACC.mean())
print('DRUG: Mean RF Test Accuracy',DRUG_RF_ACC.mean())
print('DRUG: Mean LR Test Accuracy',DRUG_LR_ACC.mean())
print('DRUG: Mean DT Test Accuracy',DRUG_DT_ACC.mean())
print('DRUG: Mean KNN Test Precision',DRUG_KNN_PREC.mean())
print('DRUG: Mean RF Test Precision',DRUG_RF_PREC.mean())
print('DRUG: Mean LR Test Precision',DRUG_LR_PREC.mean())
print('DRUG: Mean DT Test Precision',DRUG_DT_PREC.mean())

DRUG: Mean KNN Test Accuracy 0.8010609999999999
DRUG: Mean RF Test Accuracy 0.791335
DRUG: Mean LR Test Accuracy 0.810787
DRUG: Mean DT Test Accuracy 0.7736516666666667
DRUG: Mean KNN Test Precision 0.8566603333333335
DRUG: Mean RF Test Precision 0.845444
DRUG: Mean LR Test Precision 0.850183
DRUG: Mean DT Test Precision 0.8505726666666668


In [136]:
print('MUSH: Mean KNN Test Accuracy',MUSH_KNN_ACC.mean())
print('MUSH: Mean RF Test Accuracy',MUSH_RF_ACC.mean())
print('MUSH: Mean LR Test Accuracy',MUSH_LR_ACC.mean())
print('MUSH: Mean DT Test Accuracy',MUSH_DT_ACC.mean())
print('MUSH: Mean KNN Test Precision',MUSH_KNN_PREC.mean())
print('MUSH: Mean RF Test Precision',MUSH_RF_PREC.mean())
print('MUSH: Mean LR Test Precision',MUSH_LR_PREC.mean())
print('MUSH: Mean DT Test Precision',MUSH_DT_PREC.mean())

MUSH: Mean KNN Test Accuracy 1.0
MUSH: Mean RF Test Accuracy 1.0
MUSH: Mean LR Test Accuracy 0.9659490000000001
MUSH: Mean DT Test Accuracy 1.0
MUSH: Mean KNN Test Precision 1.0
MUSH: Mean RF Test Precision 1.0
MUSH: Mean LR Test Precision 0.9644233333333334
MUSH: Mean DT Test Precision 1.0


## Algorithm x Dataset

# HD

## KNN vs RF: Accuracy

In [142]:
KNN_RF_HD_accu = stats.ttest_ind(HD_KNN_ACC, HD_RF_ACC, axis=None, equal_var=False)
KNN_RF_HD_accu

Ttest_indResult(statistic=-0.3535551597406719, pvalue=0.7459558665510269)

In [143]:
print('cohens dvalue=',cohen_d(HD_RF_ACC, HD_KNN_ACC))

cohens dvalue= 0.28867657909761457


## KNN vs RF: Precision

In [144]:
KNN_RF_HD_prec = stats.ttest_ind(HD_KNN_PREC, HD_RF_PREC, axis=None, equal_var=False)
KNN_RF_HD_prec

Ttest_indResult(statistic=-1.1103870937177667, pvalue=0.36262030352411173)

In [145]:
print('cohens dvalue=',cohen_d(HD_RF_PREC, HD_KNN_PREC))

cohens dvalue= 0.906627265526831


## KNN vs LR: Accuracy

In [146]:
KNN_LR_HD_accu = stats.ttest_ind(HD_KNN_ACC, HD_LR_ACC, axis=None, equal_var=False)
KNN_LR_HD_accu

Ttest_indResult(statistic=-0.8137413768375357, pvalue=0.4625803554822158)

In [147]:
print('cohens dvalue=',cohen_d(HD_LR_ACC, HD_KNN_ACC))

cohens dvalue= 0.6644170519472682


## KNN vs LR: Precision

In [148]:
KNN_RF_LR_prec = stats.ttest_ind(HD_KNN_PREC, HD_LR_PREC, axis=None, equal_var=False)
KNN_RF_LR_prec

Ttest_indResult(statistic=-1.2478561571523064, pvalue=0.2970964559010651)

In [149]:
print('cohens dvalue=',cohen_d(HD_LR_PREC, HD_KNN_PREC))

cohens dvalue= 1.0188702858044694


## KNN vs DT: Accuracy

In [150]:
KNN_DT_HD_accu = stats.ttest_ind(HD_KNN_ACC, HD_DT_ACC, axis=None, equal_var=False)
KNN_DT_HD_accu

Ttest_indResult(statistic=0.5590157156142374, pvalue=0.6073900842686482)

In [151]:
print('cohens dvalue=',cohen_d(HD_DT_ACC, HD_KNN_ACC))

cohens dvalue= -0.4564344204838908


## KNN vs DT: Precision

In [152]:
KNN_RF_DT_prec = stats.ttest_ind(HD_KNN_PREC, HD_DT_PREC, axis=None, equal_var=False)
KNN_RF_DT_prec

Ttest_indResult(statistic=-0.10752134607996032, pvalue=0.9215603948274617)

In [153]:
print('cohens dvalue=',cohen_d(HD_DT_PREC, HD_KNN_PREC))

cohens dvalue= 0.08779081145103436


## RF vs DT: Accuracy

In [154]:
RF_DT_HD_accu = stats.ttest_ind(HD_DT_ACC, HD_RF_ACC, axis=None, equal_var=False)
RF_DT_HD_accu

Ttest_indResult(statistic=-0.7448447983539934, pvalue=0.5019168632371904)

In [155]:
print('cohens dvalue=',cohen_d(HD_RF_ACC, HD_DT_ACC))

cohens dvalue= 0.6081632311778371


## RF vs DT: Precision

In [156]:
RF_DT_HD_prec = stats.ttest_ind(HD_DT_PREC, HD_RF_PREC, axis=None, equal_var=False)
RF_DT_HD_prec

Ttest_indResult(statistic=-0.8666582697809311, pvalue=0.4383653393543635)

In [157]:
print('cohens dvalue=',cohen_d(HD_RF_PREC, HD_DT_PREC))

cohens dvalue= 0.707623514108869


## LR vs DT: Accuracy

In [158]:
LR_DT_HD_accu = stats.ttest_ind(HD_DT_PREC, HD_LR_ACC, axis=None, equal_var=False)
LR_DT_HD_accu

Ttest_indResult(statistic=-0.9556101414972289, pvalue=0.3949308403280269)

In [161]:
print('cohens dvalue=',cohen_d(HD_DT_PREC, HD_LR_ACC))

cohens dvalue= -0.7802524132323478


## LR vs DT: Precision

In [162]:
LR_DT_HD_prec = stats.ttest_ind(HD_LR_PREC, HD_DT_PREC, axis=None, equal_var=False)
LR_DT_HD_prec

Ttest_indResult(statistic=0.8214449011789557, pvalue=0.45900126116044565)

In [163]:
print('cohens dvalue=',cohen_d(HD_LR_PREC, HD_DT_PREC))

cohens dvalue= 0.6707069532331312


## LR vs RF: Accuracy

In [164]:
LR_RF_HD_accu = stats.ttest_ind(HD_LR_ACC, HD_RF_ACC, axis=None, equal_var=False)
LR_RF_HD_accu

Ttest_indResult(statistic=0.2535497379270306, pvalue=0.8140950186144977)

In [165]:
print('cohens dvalue=',cohen_d(HD_RF_PREC, HD_LR_ACC))

cohens dvalue= 0.09877329456966656


## LR vs RF: Precision

In [166]:
LR_RF_HD_prec = stats.ttest_ind(HD_LR_PREC, HD_RF_PREC, axis=None, equal_var=False)
LR_RF_HD_prec

Ttest_indResult(statistic=-0.2362065238574614, pvalue=0.826931494787057)

In [167]:
print('cohens dvalue=',cohen_d(HD_RF_PREC, HD_LR_PREC))

cohens dvalue= 0.1928618191224406


## DRUG

## KNN vs RF: Accuracy

In [168]:
KNN_RF_DRUG_accu = stats.ttest_ind(DRUG_KNN_ACC, DRUG_RF_ACC, axis=None, equal_var=False)
KNN_RF_DRUG_accu

Ttest_indResult(statistic=0.9878160559445088, pvalue=0.3795017559165384)

In [169]:
print('cohens dvalue=',cohen_d(DRUG_RF_ACC, DRUG_KNN_ACC))

cohens dvalue= -0.8065484322642027


## KNN vs RF: Precision

In [170]:
KNN_RF_DRUG_prec = stats.ttest_ind(DRUG_KNN_PREC, DRUG_RF_PREC, axis=None, equal_var=False)
KNN_RF_DRUG_prec

Ttest_indResult(statistic=0.5582197747925014, pvalue=0.6086876512535839)

In [171]:
print('cohens dvalue=',cohen_d(DRUG_RF_PREC, DRUG_KNN_PREC))

cohens dvalue= -0.4557845375243227


## KNN vs LR: Accuracy

In [172]:
KNN_LR_DRUG_accu = stats.ttest_ind(DRUG_KNN_ACC, DRUG_LR_ACC, axis=None, equal_var=False)
KNN_LR_DRUG_accu

Ttest_indResult(statistic=-1.261783121330459, pvalue=0.2911603928287743)

In [173]:
print('cohens dvalue=',cohen_d(DRUG_LR_ACC, DRUG_KNN_ACC))

cohens dvalue= 1.0302416044386338


## KNN vs LR: Precision

In [174]:
KNN_LR_DRUG_prec = stats.ttest_ind(DRUG_KNN_PREC, DRUG_LR_PREC, axis=None, equal_var=False)
KNN_LR_DRUG_prec

Ttest_indResult(statistic=0.45112788092712164, pvalue=0.6788947699081496)

In [175]:
print('cohens dvalue=',cohen_d(DRUG_LR_PREC, DRUG_KNN_PREC))

cohens dvalue= -0.36834437233816514


## KNN vs DT: Accuracy

In [176]:
KNN_DT_DRUG_accu = stats.ttest_ind(DRUG_KNN_ACC, DRUG_DT_ACC, axis=None, equal_var=False)
KNN_DT_DRUG_accu

Ttest_indResult(statistic=3.1973804210224186, pvalue=0.035116036110592434)

In [177]:
print('cohens dvalue=',cohen_d(DRUG_DT_ACC, DRUG_KNN_ACC))

cohens dvalue= -2.610650181690058


## KNN vs DT: Precision

In [178]:
KNN_DT_DRUG_prec = stats.ttest_ind(DRUG_KNN_PREC, DRUG_DT_PREC, axis=None, equal_var=False)
KNN_DT_DRUG_prec

Ttest_indResult(statistic=0.3324962513079559, pvalue=0.7564988207578975)

In [179]:
print('cohens dvalue=',cohen_d(DRUG_DT_PREC, DRUG_KNN_PREC))

cohens dvalue= -0.271482052364232


## RF vs DT: Accuracy

In [180]:
RF_DT_DRUG_accu = stats.ttest_ind(DRUG_DT_ACC, DRUG_RF_ACC, axis=None, equal_var=False)
RF_DT_DRUG_accu

Ttest_indResult(statistic=-1.9611506869039437, pvalue=0.12727373774997788)

In [181]:
print('cohens dvalue=',cohen_d(DRUG_RF_ACC, DRUG_DT_ACC))

cohens dvalue= 1.6012728305411317


## RF vs DT: Precision

In [182]:
RF_DT_DRUG_prec = stats.ttest_ind(DRUG_DT_PREC, DRUG_RF_PREC, axis=None, equal_var=False)
RF_DT_DRUG_prec

Ttest_indResult(statistic=0.24202752354030063, pvalue=0.8209241098500546)

In [183]:
print('cohens dvalue=',cohen_d(DRUG_RF_PREC, DRUG_DT_PREC))

cohens dvalue= -0.1976146454610602


## LR vs DT: Accuracy

In [184]:
LR_DT_DRUG_accu = stats.ttest_ind(DRUG_LR_ACC, DRUG_DT_ACC, axis=None, equal_var=False)
LR_DT_DRUG_accu

Ttest_indResult(statistic=5.612706494511078, pvalue=0.006604932033807754)

In [185]:
print('cohens dvalue=',cohen_d(DRUG_LR_ACC, DRUG_DT_ACC))

cohens dvalue= 4.582755662519138


## LR vs DT: Precision

In [186]:
LR_DT_DRUG_prec = stats.ttest_ind(DRUG_LR_PREC, DRUG_DT_PREC, axis=None, equal_var=False)
LR_DT_DRUG_prec

Ttest_indResult(statistic=-0.024573106406012388, pvalue=0.9818630354160409)

In [187]:
print('cohens dvalue=',cohen_d(DRUG_LR_PREC, DRUG_DT_PREC))

cohens dvalue= -0.020063857363282315


## LR vs RF: Accuracy

In [188]:
LR_RF_DRUG_accu = stats.ttest_ind(DRUG_LR_ACC, DRUG_RF_ACC, axis=None, equal_var=False)
LR_RF_DRUG_accu

Ttest_indResult(statistic=2.372340863330464, pvalue=0.09687959627134225)

In [189]:
print('cohens dvalue=',cohen_d(DRUG_RF_ACC, DRUG_LR_ACC))

cohens dvalue= -1.9370082037044531


## LR vs RF: Precision

In [190]:
LR_RF_DRUG_prec = stats.ttest_ind(DRUG_LR_PREC, DRUG_RF_PREC, axis=None, equal_var=False)
LR_RF_DRUG_prec

Ttest_indResult(statistic=0.26493049568131743, pvalue=0.8087951135043198)

In [191]:
print('cohens dvalue=',cohen_d(DRUG_RF_PREC, DRUG_LR_PREC))

cohens dvalue= -0.2163148439072834


## MUSH

## KNN vs RF: Accuracy

In [209]:
KNN_RF_MUSH_accu = stats.ttest_ind(MUSH_KNN_ACC, MUSH_RF_ACC, axis=None, equal_var=False)
KNN_RF_MUSH_accu

Ttest_indResult(statistic=nan, pvalue=nan)

In [210]:
print('cohens dvalue=',cohen_d(MUSH_RF_ACC, MUSH_KNN_ACC))

cohens dvalue= nan


## KNN vs RF: Precision

In [211]:
KNN_RF_MUSH_prec = stats.ttest_ind(MUSH_KNN_PREC, MUSH_RF_PREC, axis=None, equal_var=False)
KNN_RF_MUSH_prec

Ttest_indResult(statistic=nan, pvalue=nan)

In [212]:
print('cohens dvalue=',cohen_d(MUSH_RF_PREC, MUSH_KNN_PREC))

cohens dvalue= nan


## KNN vs LR: Accuracy

In [213]:
KNN_LR_MUSH_accu = stats.ttest_ind(MUSH_KNN_ACC, MUSH_LR_ACC, axis=None, equal_var=False)
KNN_LR_MUSH_accu

Ttest_indResult(statistic=9.867811942901652, pvalue=0.010114171688412693)

In [214]:
print('cohens dvalue=',cohen_d(MUSH_LR_ACC, MUSH_KNN_ACC))

cohens dvalue= -8.05703471261698


## KNN vs LR: Precision

In [215]:
KNN_LR_MUSH_prec = stats.ttest_ind(MUSH_KNN_PREC, MUSH_LR_PREC, axis=None, equal_var=False)
KNN_LR_MUSH_prec

Ttest_indResult(statistic=6.096541563699798, pvalue=0.025865680421298096)

In [216]:
print('cohens dvalue=',cohen_d(MUSH_LR_PREC, MUSH_KNN_PREC))

cohens dvalue= -4.9778053422446575


## KNN vs DT: Accuracy

In [217]:
KNN_DT_MUSH_accu = stats.ttest_ind(MUSH_KNN_ACC, MUSH_DT_ACC, axis=None, equal_var=False)
KNN_DT_MUSH_accu

Ttest_indResult(statistic=nan, pvalue=nan)

In [218]:
print('cohens dvalue=',cohen_d(MUSH_DT_ACC, MUSH_KNN_ACC))

cohens dvalue= nan


## KNN vs DT: Precision

In [219]:
KNN_DT_MUSH_prec = stats.ttest_ind(MUSH_KNN_PREC, MUSH_DT_PREC, axis=None, equal_var=False)
KNN_DT_MUSH_prec

Ttest_indResult(statistic=nan, pvalue=nan)

In [220]:
print('cohens dvalue=',cohen_d(MUSH_DT_PREC, MUSH_KNN_PREC))

cohens dvalue= nan


## RF vs DT: Accuracy

In [221]:
RF_DT_MUSH_accu = stats.ttest_ind(MUSH_DT_ACC, MUSH_RF_ACC, axis=None, equal_var=False)
RF_DT_MUSH_accu

Ttest_indResult(statistic=nan, pvalue=nan)

In [222]:
print('cohens dvalue=',cohen_d(MUSH_RF_ACC, MUSH_DT_ACC))

cohens dvalue= nan


## RF vs DT: Precision

In [223]:
RF_DT_MUSH_prec = stats.ttest_ind(MUSH_DT_PREC, MUSH_RF_PREC, axis=None, equal_var=False)
RF_DT_MUSH_prec

Ttest_indResult(statistic=nan, pvalue=nan)

In [224]:
print('cohens dvalue=',cohen_d(MUSH_RF_PREC, MUSH_DT_PREC))

cohens dvalue= nan


## LR vs DT: Accuracy

In [225]:
LR_DT_MUSH_accu = stats.ttest_ind(MUSH_LR_ACC, MUSH_DT_ACC, axis=None, equal_var=False)
LR_DT_MUSH_accu

Ttest_indResult(statistic=-9.867811942901652, pvalue=0.010114171688412693)

In [226]:
print('cohens dvalue=',cohen_d(MUSH_LR_ACC, MUSH_DT_ACC))

cohens dvalue= -8.05703471261698


## LR vs DT: Precision

In [227]:
LR_DT_MUSH_prec = stats.ttest_ind(MUSH_LR_PREC, MUSH_DT_PREC, axis=None, equal_var=False)
LR_DT_MUSH_prec

Ttest_indResult(statistic=-6.096541563699798, pvalue=0.025865680421298096)

In [228]:
print('cohens dvalue=',cohen_d(MUSH_LR_PREC, MUSH_DT_PREC))

cohens dvalue= -4.9778053422446575


## LR vs RF: Accuracy

In [229]:
LR_RF_MUSH_accu = stats.ttest_ind(MUSH_LR_ACC, MUSH_RF_ACC, axis=None, equal_var=False)
LR_RF_MUSH_accu

Ttest_indResult(statistic=-9.867811942901652, pvalue=0.010114171688412693)

In [230]:
print('cohens dvalue=',cohen_d(MUSH_RF_ACC, MUSH_LR_ACC))

cohens dvalue= 8.05703471261698


## LR vs RF: Precision

In [231]:
LR_RF_MUSH_prec = stats.ttest_ind(MUSH_LR_PREC, MUSH_RF_PREC, axis=None, equal_var=False)
LR_RF_MUSH_prec

Ttest_indResult(statistic=-6.096541563699798, pvalue=0.025865680421298096)

In [232]:
print('cohens dvalue=',cohen_d(MUSH_RF_PREC, MUSH_LR_PREC))

cohens dvalue= 4.9778053422446575
